#!/usr/bin/env python
import os
import sys
from bottle import Bottle, TEMPLATE_PATH, view, static_file, error

# http://stackoverflow.com/questions/10693695/loading-static-files-in-a-bottle-py-application-on-openshift
# OPENSHIFT ENVIRONMENT VARIABLES: https://www.openshift.com/page/openshift-environment-variables
TEMPLATE_PATH.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi/views/'))

#https://www.openshift.com/forums/openshift/how-to-install-a-custom-python-package
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "wsgi"))

from mybottleapp import *

